### ISSUE TITLE
Disable Resource Packs

### ISSUE THREAD

**Issue by Timongcraft** [TheMysterys/Server-Pack-Unlocker#1]
Hello,
I think your mod is broken because I have 1.19.2 and I'm on a server with forced resource pack and I can't disable it in the options.

**Comment by Timong-craft** [comment]
I think I can move it but I can't disable it.
If that is not a feature then ok but it would be nice if you add it.

**Comment by TheMysterys** [comment]
To disable a resource pack you just need to put it below Default (While some things might still work like if the mod uses custom fonts) pretty much all features from the pack will be disabled 
(Not exactly possible to completely disable the pack due to it needing to be downloaded to join servers)

**Comment by Timong-craft** [comment]
That's right but can't you tell the server that the client loaded the pack but it doesn't?
Beacause what I want is that I can join a server that forces a pack and that I don't have to use it aka can disable it in the settings of the server in the multiplayer menu. So you don't have to load the pack everytime I join and leave the server.

**Comment by TheMysterys** [comment]
I'll look into it but I'm pretty sure that if I make the mod accept the resource pack, the server will send it none the less (making the client download it)

**Comment by Julienraptor01** [comment]
> To disable a resource pack you just need to put it below Default (While some things might still work like if the pack uses custom fonts) pretty much all features from the pack will be disabled (Not exactly possible to completely disable the pack due to it needing to be downloaded to join servers)

technically it's possible to disable the pack and make the server still thinks you have the pack...
however it's a cheat client feature and i'm pretty sure it doesn't comply with modrinth guidelines and would make this mod banned

**Comment by Timong-craft** [comment]
Yea, well did'n thougth about ut that way but I only searched for that feature because the loading annoyed me.

**Comment by Julienraptor01** [comment]
> Yea, well did'n thougth about ut that way but I only searched for that feature because the loading annoyed me.

I agree too

**Comment by TheMysterys** [comment]
Added this in version 1.1. You will have to manually change the config setting from true to false (which also requires restarting the client)
https://modrinth.com/mod/server-pack-unlocker/version/1.1

**Comment by Timong-craft** [comment]
Yea thats cool but now if I enable a resource pack on a server it doesn't work (with the config change) and I thought that I can choose but don't be forced but this is also fine. Thanks

**Comment by TheMysterys** [comment]
Feel free to provide more information and I'll look into expanding it where possible. 

At the moment you still have to enable server resource packs (in server settings) but the mod will just ignore the downloading/applying it

I might in the future add an option like the enable server resource pack (in server settings) to allow for per server configuration but for now it's not planned
