### ISSUE TITLE
doesnt work on mcc island

### ISSUE THREAD

**Issue by skibidibada** [TheMysterys/Server-Pack-Unlocker#10]
basically the title, im not able to move their server pack below my one

**Comment by TheMysterys** [comment]
Could you explain what you mean cause I just tested it with the latest version and it works

![image](https://github.com/TheMysterys/Server-Pack-Unlocker/assets/42754166/ad9ec9c4-cb81-43ce-a385-bb5b70856499)
![image](https://github.com/TheMysterys/Server-Pack-Unlocker/assets/42754166/4726eed3-6241-42bc-af3e-4a528fa2b6e9)

**Comment by TheMysterys** [comment]
Also please make sure you've actually got the mod installed

**Comment by skibidibada** [comment]
> Also please make sure you've actually got the mod installed

I did have the mod installed, for some reason instead of dragging i had to do a slightly different way of moving it, altough now if the mcc pack is below any other pack mcci kicks me from the server, is there a way to fix this?

**Comment by TheMysterys** [comment]
Could you send though your log file using this site (it removed sensitive information)

https://mclo.gs

**Comment by TheMysterys** [comment]
Please provide an update on this @skibidibada, otherwise I can't help

**Comment by skibidibada** [comment]
![2023-10-15_18 00 24](https://github.com/TheMysterys/Server-Pack-Unlocker/assets/111621104/580c091c-0c4c-4c24-92fb-174211ab9d84)
okay so i cant replicate the issue anymore, i went on a new instance and everything was good, altough there is this thing that is still on my screen when i am in my instance where i have 100 other mods, but this isnt the issue with this mod specifically i dont think

**Comment by JanCantCode** [comment]
same issue for me, using v1.6 on minecraft 1.20.1, disabling of the ressourcepack on this server does nothing ^

**Comment by TheMysterys** [comment]
Reopen if issues still exist
