### ISSUE TITLE
Incompatibility with Recursive Resources Mod

### ISSUE THREAD

**Issue by DB20-official** [TheMysterys/Server-Pack-Unlocker#11]
## Description
It appears that Recursive Resources is preventing Server Pack Unlocker from moving the server's resource pack below any client-side packs.
## Expected Behavior
Server pack can be overridden with client resource packs, even with Recursive Resources installed.
## Actual Behavior
When attempting to override a server resource pack with any client resource pack with Recursive Resources installed and then reloading, the server pack is forced back to the top without warning.
## To Reproduce
- Install Server Pack Unlocker 1.6 and Recursive Resources 2.5.2 for Minecraft 1.20.x.
- Connect to any server with a resource pack that modify menu GUIs (needed to see the bug in effect).
- Head to the Resource Packs Screen
- Move any pack (including Default) of your choosing above the server's pack.
- Click "Done."
- Server resource packs remain atop other packs after reload and sometimes the reload won't happen at all, instantly undoing changes.
## Versions Tested
- Minecraft Fabric 1.20.1
- Server Pack Unlocker v1.6
- Recursive Resources 2.5.2 (the conflicting mod)
## More Information
If needed, an issue may also be made on the GitHub repo for Recursive Resources (https://github.com/enjarai/recursive-resources) regarding this incompatibility.

**Comment by TheMysterys** [comment]
I'll take a look and see if there's anything I can do on my end to fix this. Quite a weird bug though

**Comment by rayhanhamada93** [comment]
is there any updates regarding this issue?

**Comment by TheMysterys** [comment]
No updates sorry, In a busy period of my life so haven't had a chance.

**Comment by TheMysterys** [comment]
Having tested this with the new updated it seems this has been fixed.
