### ISSUE TITLE
Game instantly crashes upon clicking Multiplayer

### ISSUE THREAD

**Issue by Quadragintillion** [TheMysterys/Server-Pack-Unlocker#13]
I am using:
- fabric-loader-0.14.22-1.19.4
- fabric-api-0.87.0+1.19.4
When I click on Multiplayer, my game immediately crashes.

**Comment by Quadragintillion** [comment]
This is also happening for
- fabric-loader-0.14.21-1.20.1
- fabric-api-0.88.1+1.20.1

**Comment by TheMysterys** [comment]
Can you please provide a crash log and game log. 
https://mclo.gs

**Comment by Quadragintillion** [comment]
I restarted my computer and it seemed to fix itself. The mod works now. It was likely an issue with Java, not the mod.
