### ISSUE TITLE
Support for 1.20.4

### ISSUE THREAD

**Issue by SJ-Tom** [TheMysterys/Server-Pack-Unlocker#17]
I am using the mod nearly every day by developing server resource packs, and it would be nice to get these feature in the latest minecraft version 1.20.4

**Comment by skyeredwood** [comment]
seconding this, 1.20.4 update is very needed especially as more versions are coming soon

**Comment by SJ-Tom** [comment]
I think that this mod will no longer be maintained, as the last update was some time ago

**Comment by TheMysterys** [comment]
Updated. Sorry for taking forever and ever
