### ISSUE TITLE
Incompatibility with Wynntils mod

### ISSUE THREAD

**Issue by Rafii2198** [TheMysterys/Server-Pack-Unlocker#18]
Wynntils is a mod dedicated for Wynncraft server. One of it's features is to load the Wynncraft resource pack when launching minecraft so that it doesn't have to reload when joining the server, adding unnecessary loading time (especially with another Auto Connect feature) as well as Wynncraft ascetics on main menu.

The issue is that the resourcepack loaded by Wynntils is not movable by this mod at all. If someone wanted to use Server Pack Unlocker then they would have to disable the Auto Load Resourcepack feature in Wynntils which is handy.
I recently found a similar mod, [Serverpack Priority](https://modrinth.com/mod/serverpack-priority) which just moves serverpacks to the bottom of the list but above the fabric resources, and it works with Wynntils Auto Loading feature with no issues which leads me to believe the issue is not on Wynntils side unless Server Priority included special code just for Wynntils.

**Comment by TheMysterys** [comment]
Should be fixed now with 1.8. Will be closing this now
