### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by SJ-Tom** [TheMysterys/Server-Pack-Unlocker#21]
As with #17, a new version has been released, and we need a new update for the mod

**Comment by TheMysterys** [comment]
Have you checked if current version works since it should hopefully not require any changes. 

But I'll test it tomorrow anyhow and update if necessary

**Comment by TheMysterys** [comment]
Have checked. Version 1.8 supports 1.21 so will update the supported versions on Modrinth
