### ISSUE TITLE
Wrong chest gui texture loading

### ISSUE THREAD

**Issue by Limit-sest** [TheMysterys/Server-Pack-Unlocker#5]
I have this problem that the server I'm playing on have forced resource pack and i want a dark gui. So, i go to the resource pack menu and put my dark mode rp above the server one. But the server rp have texture for double chest which mine has too. 
![image](https://user-images.githubusercontent.com/81852696/232319192-59458299-787b-4517-9aaf-01a997b96ee7.png) ![image](https://user-images.githubusercontent.com/81852696/232319232-899f6393-7e09-4f63-a06d-82ea7272efb9.png)

So it kinda "mixes" together and it looks like this:
![image](https://user-images.githubusercontent.com/81852696/232319366-97c606cf-87d4-4f95-a295-d8ebc642cade.png)

Do you have any clue why is this happening?

**Comment by TheMysterys** [comment]
Could you send the server IP, and I'll get back to you ASAP

**Comment by Limit-sest** [comment]
Alright, here is the server resource pack.
[ac28d6a415684d8e7db4e7f1ec97321f21025832 - Copy.zip](https://github.com/TheMysterys/Server-Pack-Unlocker/files/11243290/ac28d6a415684d8e7db4e7f1ec97321f21025832.-.Copy.zip)
And this is the resource pack i wanted to use:
[Default-Dark-Mode-1.19.3-0-0FFF00-1-FFA700-FFA700-(v1.4.0).zip](https://github.com/TheMysterys/Server-Pack-Unlocker/files/11243293/Default-Dark-Mode-1.19.3-0-0FFF00-1-FFA700-FFA700-.v1.4.0.zip)

**Comment by TheMysterys** [comment]
Hi there, could you send me the non (attempted) extracted version of the resource pack

**Comment by TheMysterys** [comment]
Okay so looks like they are using custom textures for chest guis, (which I suspected but looking at the pack confirms) which is weird cause it's just a normal chest and all. 

All you need to do is recreate these files in your pack at the same path:
`assets\minecraft\textures\custom\ui\single_chest.png` and `assets\minecraft\textures\custom\ui\double_chest.png`

They use the same texture, just single chest is shorter.

**Comment by Limit-sest** [comment]
Okay, i did it but there is a another problem. I copied the `generic_54.png` and renamed it to the `double_chest.png` but for some reason, the new texture is slightly higher.
![image](https://user-images.githubusercontent.com/81852696/232384139-e0ec3019-49cf-4239-99c3-8f334b2cf1c8.png)
Do you know what could be doing this?

**Comment by TheMysterys** [comment]
So, they aren't using the same texture as `generic_54.png` but just a custom texture of just the top half of the GUI. I can't really help more than this, since I don't want to reveal parts of their texture pack which they've tried to hide/prevent accessing.

**Comment by Limit-sest** [comment]
Ok, i will do it myself. But thanks for leading  me in the right direction and helping me!
