### ISSUE TITLE
Infinite loading screen when adding a RP above server RP

### ISSUE THREAD

**Issue by Andre601** [TheMysterys/Server-Pack-Unlocker#8]
Tried to apply a Resource pack above the server resource pack. But while doing so was my client stuck in an infinite loading screen.
The loading bar was stuck at around 95% (guessing. There was no visible percentage).

Loading the RP without the mod enabled is loading perfectly fine.

Full client log: https://mclo.gs/0bsYNVs

**Comment by TheMysterys** [comment]
Could you tell me what your pack settings were in the server info page, a copy of your `.minecraft\config\Server-Pack-Unlocker\pack-order.json` file and the number of resource packs enabled.

**Comment by Andre601** [comment]
> Could you tell me what your pack settings were in the server info page, a copy of your `.minecraft\config\Server-Pack-Unlocker\pack-order.json` file and the number of resource packs enabled.
> 
> Also if you can grab a screen capture of you repeating your steps that would be amazing (or list them)

The setting was prompt when I initially added the server. At the time of using this mod did I join the server before so it was accept pretty much as it no longer gave me any prompts to download.

Full content of the JSON file: `{"spectrum.originrealms.com":6}`

Steps to reproduce:

1. Install the mod
2. Add the resource pack that should go above the Server pack
3. Join the server and wait until everything is loaded
4. Move the RP from the left to the right column to activate it and finish.
5. Encounter infite loading

Also, one small note that may be of importance is, that the resource pack is encoded (Has files protected from extraction). This is not really by the choice of the author, but rather a requirement from the server to not get into copyright issues, as they themself protect their RP and the one I want to use overrides some models and textures...

Also, the RP uses features for custom entity textures and models, which I use EMF and ETF for.

Not sure if any of these info is of importance to you. Not sure how you actually keep track of the RP order as the JSON doesn't seem to hold any important info regarding this...

**Comment by TheMysterys** [comment]
Sorry for the late response, could you send a link to the rp you're trying to load

Also yeah I'm familiar with OR's pack and shouldn't be a problem

**Comment by TheMysterys** [comment]
Okay I'm going to have to do some testing. I'm not sure if it's something to do with the pack, or one of the mods you're using but I'll try work this out as soon as possible. But over the next 2 weeks I have exams so it will take a while.

**Comment by TheMysterys** [comment]
Honestly couldn't work out why this happens. But I'll leave this open to see if someone else can find a fix

**Comment by GlitchSlayed** [comment]
It seems to happen to any pack you try to use to override on the origin realms server as i am having the same issue and tried a few different packs

**Comment by g020276j** [comment]
It's happening with me now also

**Comment by g020276j** [comment]
The Continuity mod appears to be the culprit, at least from my testing on OriginRealms with OR Tweaks, MC Version 1.20.1

**Comment by TheMysterys** [comment]
Should be fixed due to this feature now being removed
